apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
  labels:
    app: backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend-container
          image: 905418026158.dkr.ecr.us-east-1.amazonaws.com/shopping-site-backend:5b762c3ff04dcded30b28cf594989989d535d661
          ports:
            - containerPort: 5000
