apiVersion: apps/v1
kind: Deployment
metadata:
  name: electronics-deployment
  labels:
    app: electronics
spec:
  replicas: 2
  selector:
    matchLabels:
      app: electronics
  template:
    metadata:
      labels:
        app: electronics
    spec:
      containers:
      - name: electronics
        image: 905418310012.dkr.ecr.us-west-2.amazonaws.com/shopping-site-electronics:f2efc2aa1776805c4d800d58c39592991d8b1af7
        ports:
        - containerPort: 80
