apiVersion: apps/v1
kind: Deployment
metadata:
  name: main-frontend-deployment
  labels:
    app: main-frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: main-frontend
  template:
    metadata:
      labels:
        app: main-frontend
    spec:
      containers:
      - name: main-frontend
        image: 905418310012.dkr.ecr.us-west-2.amazonaws.com/shopping-site-main:f2efc2aa1776805c4d800d58c39592991d8b1af7
        ports:
        - containerPort: 80

