apiVersion: apps/v1
kind: Deployment
metadata:
  name: googlemusic-deployment
  labels:
    app: googlemusic
spec:
  replicas: 2
  selector:
    matchLabels:
      app: googlemusic
  template:
    metadata:
      labels:
        app: googlemusic
    spec:
      containers:
      - name: googlemusic
        image: 905418310012.dkr.ecr.us-west-2.amazonaws.com/shopping-site-googlemusic:f2efc2aa1776805c4d800d58c39592991d8b1af7
        ports:
        - containerPort: 80
