apiVersion: apps/v1
kind: Deployment
metadata:
  name: phones-deployment
  labels:
    app: phones
spec:
  replicas: 2
  selector:
    matchLabels:
      app: phones
  template:
    metadata:
      labels:
        app: phones
    spec:
      containers:
      - name: phones
        image: 905418310012.dkr.ecr.us-west-2.amazonaws.com/shopping-site-phones:f2efc2aa1776805c4d800d58c39592991d8b1af7
        ports:
        - containerPort: 80
