name: CI/CD for Shopping Site (Frontend + Backend)

on:
push:
branches:
- main

env:
AWS_REGION: us-east-1
ECR_REGISTRY: ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.us-east-1.amazonaws.com
FRONTEND_SERVICES: "main electronics phones computers earphones googlemusic googlepay googleclothes googlegrocery"

permissions:
contents: write

jobs:
deploy:
runs-on: ubuntu-latest

```
steps:
  # Checkout
  - name: Checkout
    uses: actions/checkout@v4

  # AWS Credentials
  - name: Configure AWS credentials
    uses: aws-actions/configure-aws-credentials@v4
    with:
      aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
      aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      aws-region: ${{ env.AWS_REGION }}

  # ECR Login
  - name: Login to Amazon ECR
    uses: aws-actions/amazon-ecr-login@v2

  # Build & Push
  - name: Build and Push Docker Images
    run: |
      set -e
      IMAGE_TAG="${GITHUB_SHA}"
      echo "Using IMAGE TAG: $IMAGE_TAG"

      # Frontend
      for service in $FRONTEND_SERVICES; do
        FOLDER="frontend/$service"
        REPO_NAME="shopping-site-$service"
        IMAGE_URI="$ECR_REGISTRY/$REPO_NAME:$IMAGE_TAG"

        if [ ! -f "$FOLDER/Dockerfile" ]; then
          echo "Skipping $service"
          continue
        fi

        aws ecr describe-repositories --repository-names $REPO_NAME >/dev/null 2>&1 || \
          aws ecr create-repository --repository-name $REPO_NAME

        docker build -t $IMAGE_URI $FOLDER
        docker push $IMAGE_URI

        sed -i "0,/image:/s|image:.*|image: $IMAGE_URI|" "$FOLDER/deployment.yml"
      done

      # Backend
      FOLDER="backend"
      REPO_NAME="shopping-site-backend"
      IMAGE_URI="$ECR_REGISTRY/$REPO_NAME:$IMAGE_TAG"

      aws ecr describe-repositories --repository-names $REPO_NAME >/dev/null 2>&1 || \
        aws ecr create-repository --repository-name $REPO_NAME

      docker build -t $IMAGE_URI $FOLDER
      docker push $IMAGE_URI

      sed -i "0,/image:/s|image:.*|image: $IMAGE_URI|" "$FOLDER/backend-deployment.yml"

  # Commit changes
  - name: Commit updated YAML
    run: |
      git config --global user.name "GitHub Actions"
      git config --global user.email "actions@github.com"

      git add frontend/**/deployment.yml backend/backend-deployment.yml
      git commit -m "update image [skip ci]" || echo "No changes"
      git push

  # Prevent loop
  - name: Skip loop
    if: contains(github.event.head_commit.message, '[skip ci]')
    run: echo "Skipping"
```
